[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18" # Specify a Node.js version compatible with your project

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
